from PIL import Image
base_img=Image.open("base.jpeg")
img_filter=Image.open("download.jpeg")
size=(760,760)
base_img=base_img.resize(size)
img_filter=img_filter.resize(size)
r,g,b=base_img.split()
R,G,B=img_filter.split()
im=Image.merge("RGB",(R,g,B))
im.show()
#im.save('1_merged.jpg')
